#This dockerfile uses the ubuntu image
FROM ubuntu:14.04

MAINTAINER uniray7 uniray7@gmail.com

# install basic packages
RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y git
RUN apt-get update
RUN apt-get install -y build-essential
